name: Eleventy Build
on:
  push:
    branches:
      - master 
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          install_dependencies: true
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: JamPack the site
        run: |
          npm install @divriots/jampack
          npx @divriots/jampack public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: public
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
